{% set name = "agilent-format" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8c0927309d8952d20741bb27adf49fb96007c720cfdca84a35b423d87090c4e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - agilent_format
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: File reader for Agilent Resolutions Pro FT-IR images
  license: MIT
  license_file: LICENSE
  home: https://github.com/stuart-cls/python-agilent-file-formats
  description: Python library for reading FT-IR imaging datasets created by Resolutions Pro on Agilent Cary instruments with FPA area detectors. Developed for use in the orange-spectroscopy add-in, which is part of the Quasar data analysis program.

extra:
  recipe-maintainers:
    - HeavyTony2
